# Form implementation generated from reading ui file '../ui/statistic.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowStatistic(object):
    def setupUi(self, WindowStatistic):
        WindowStatistic.setObjectName("WindowStatistic")
        WindowStatistic.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        WindowStatistic.resize(1124, 759)
        WindowStatistic.setStyleSheet("background-color: rgb(252, 217, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=WindowStatistic)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 30, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 530, 131, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../ui/../pictures/horse_back.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pb_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_back.setGeometry(QtCore.QRect(30, 530, 131, 131))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        self.pb_back.setFont(font)
        self.pb_back.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 2px solid black;")
        self.pb_back.setObjectName("pb_back")
        self.l_diagramm = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_diagramm.setGeometry(QtCore.QRect(210, 140, 671, 501))
        self.l_diagramm.setText("")
        self.l_diagramm.setPixmap(QtGui.QPixmap("../ui/../statistic/statistic_result.png"))
        self.l_diagramm.setScaledContents(True)
        self.l_diagramm.setObjectName("l_diagramm")
        WindowStatistic.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WindowStatistic)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 23))
        self.menubar.setObjectName("menubar")
        WindowStatistic.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WindowStatistic)
        self.statusbar.setObjectName("statusbar")
        WindowStatistic.setStatusBar(self.statusbar)

        self.retranslateUi(WindowStatistic)
        QtCore.QMetaObject.connectSlotsByName(WindowStatistic)

    def retranslateUi(self, WindowStatistic):
        _translate = QtCore.QCoreApplication.translate
        WindowStatistic.setWindowTitle(_translate("WindowStatistic", "Vokabeltrainer"))
        self.label.setText(_translate("WindowStatistic", "Statistik"))
        self.pb_back.setText(_translate("WindowStatistic", "Zurück"))
