# Form implementation generated from reading ui file '../ui/window_vocabulary_delete_folder.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowVocabularyDeleteFolder(object):
    def setupUi(self, WindowVocabularyDeleteFolder):
        WindowVocabularyDeleteFolder.setObjectName("WindowVocabularyDeleteFolder")
        WindowVocabularyDeleteFolder.resize(1124, 759)
        WindowVocabularyDeleteFolder.setStyleSheet("background-color: rgb(252, 217, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=WindowVocabularyDeleteFolder)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 10, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 991, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 191, 991, 461))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.pb_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_back.setGeometry(QtCore.QRect(910, 40, 131, 131))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        self.pb_back.setFont(font)
        self.pb_back.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 2px solid black;")
        self.pb_back.setObjectName("pb_back")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(910, 40, 131, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../ui/../pictures/horse_back.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.label_2.raise_()
        self.listWidget.raise_()
        self.label_3.raise_()
        self.pb_back.raise_()
        WindowVocabularyDeleteFolder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WindowVocabularyDeleteFolder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 23))
        self.menubar.setObjectName("menubar")
        WindowVocabularyDeleteFolder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WindowVocabularyDeleteFolder)
        self.statusbar.setObjectName("statusbar")
        WindowVocabularyDeleteFolder.setStatusBar(self.statusbar)

        self.retranslateUi(WindowVocabularyDeleteFolder)
        QtCore.QMetaObject.connectSlotsByName(WindowVocabularyDeleteFolder)

    def retranslateUi(self, WindowVocabularyDeleteFolder):
        _translate = QtCore.QCoreApplication.translate
        WindowVocabularyDeleteFolder.setWindowTitle(_translate("WindowVocabularyDeleteFolder", "Vokabeltrainer"))
        self.label.setText(_translate("WindowVocabularyDeleteFolder", "Vokabeln löschen"))
        self.label_2.setText(_translate("WindowVocabularyDeleteFolder", "In welchen Ordner möchten Sie Vokabeln löschen?"))
        self.pb_back.setText(_translate("WindowVocabularyDeleteFolder", "Zurück"))
