# Form implementation generated from reading ui file '../ui/window_vocabularies_delete.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowVocabulariesDelete(object):
    def setupUi(self, WindowVocabulariesDelete):
        WindowVocabulariesDelete.setObjectName("WindowVocabulariesDelete")
        WindowVocabulariesDelete.resize(1124, 759)
        WindowVocabulariesDelete.setStyleSheet("background-color: rgb(252, 217, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=WindowVocabulariesDelete)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(180, 70, 731, 591))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 530, 131, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../ui/../pictures/horse_back.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pb_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_back.setGeometry(QtCore.QRect(30, 530, 131, 131))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        self.pb_back.setFont(font)
        self.pb_back.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 2px solid black;")
        self.pb_back.setObjectName("pb_back")
        WindowVocabulariesDelete.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WindowVocabulariesDelete)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 23))
        self.menubar.setObjectName("menubar")
        WindowVocabulariesDelete.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WindowVocabulariesDelete)
        self.statusbar.setObjectName("statusbar")
        WindowVocabulariesDelete.setStatusBar(self.statusbar)

        self.retranslateUi(WindowVocabulariesDelete)
        QtCore.QMetaObject.connectSlotsByName(WindowVocabulariesDelete)

    def retranslateUi(self, WindowVocabulariesDelete):
        _translate = QtCore.QCoreApplication.translate
        WindowVocabulariesDelete.setWindowTitle(_translate("WindowVocabulariesDelete", "Vokabeltrainer"))
        self.label.setText(_translate("WindowVocabulariesDelete", "Vokabeln löschen"))
        self.pb_back.setText(_translate("WindowVocabulariesDelete", "Zurück"))
