# Form implementation generated from reading ui file '../ui/window_write_vocabularies.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowWriteVocabularies(object):
    def setupUi(self, WindowWriteVocabularies):
        WindowWriteVocabularies.setObjectName("WindowWriteVocabularies")
        WindowWriteVocabularies.resize(1124, 759)
        WindowWriteVocabularies.setStyleSheet("background-color: rgb(252, 217, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=WindowWriteVocabularies)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 530, 131, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../ui/../pictures/horse_back.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pb_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_back.setGeometry(QtCore.QRect(30, 530, 131, 131))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        self.pb_back.setFont(font)
        self.pb_back.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 2px solid black;")
        self.pb_back.setObjectName("pb_back")
        self.l_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_text.setGeometry(QtCore.QRect(480, 280, 171, 61))
        self.l_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l_text.setObjectName("l_text")
        self.l_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.l_input.setGeometry(QtCore.QRect(360, 350, 431, 101))
        self.l_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l_input.setObjectName("l_input")
        self.l_card = QtWidgets.QLabel(parent=self.centralwidget)
        self.l_card.setGeometry(QtCore.QRect(360, 90, 431, 191))
        self.l_card.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.l_card.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l_card.setObjectName("l_card")
        self.pb_check = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_check.setGeometry(QtCore.QRect(480, 470, 181, 51))
        self.pb_check.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pb_check.setObjectName("pb_check")
        self.pb_card = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_card.setGeometry(QtCore.QRect(360, 90, 431, 191))
        self.pb_card.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 1px solid black;")
        self.pb_card.setText("")
        self.pb_card.setObjectName("pb_card")
        self.pb_statistic = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_statistic.setGeometry(QtCore.QRect(870, 180, 181, 51))
        self.pb_statistic.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pb_statistic.setObjectName("pb_statistic")
        WindowWriteVocabularies.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WindowWriteVocabularies)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 23))
        self.menubar.setObjectName("menubar")
        WindowWriteVocabularies.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WindowWriteVocabularies)
        self.statusbar.setObjectName("statusbar")
        WindowWriteVocabularies.setStatusBar(self.statusbar)

        self.retranslateUi(WindowWriteVocabularies)
        QtCore.QMetaObject.connectSlotsByName(WindowWriteVocabularies)

    def retranslateUi(self, WindowWriteVocabularies):
        _translate = QtCore.QCoreApplication.translate
        WindowWriteVocabularies.setWindowTitle(_translate("WindowWriteVocabularies", "Vokabeltrainer"))
        self.label.setText(_translate("WindowWriteVocabularies", "Vokabeln schreiben"))
        self.pb_back.setText(_translate("WindowWriteVocabularies", "Zurück"))
        self.l_text.setText(_translate("WindowWriteVocabularies", "Übersetzung:"))
        self.l_card.setText(_translate("WindowWriteVocabularies", "Vokabel"))
        self.pb_check.setText(_translate("WindowWriteVocabularies", "Überprüfen"))
        self.pb_check.setShortcut(_translate("WindowWriteVocabularies", "Return"))
        self.pb_statistic.setText(_translate("WindowWriteVocabularies", "Statistik"))
