# Form implementation generated from reading ui file '../ui/window_add_vocabularies_name_folder.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowAddVocabulariesNameFolder(object):
    def setupUi(self, WindowAddVocabulariesNameFolder):
        WindowAddVocabulariesNameFolder.setObjectName("WindowAddVocabulariesNameFolder")
        WindowAddVocabulariesNameFolder.resize(1124, 759)
        WindowAddVocabulariesNameFolder.setStyleSheet("background-color: rgb(252, 217, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=WindowAddVocabulariesNameFolder)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 651, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(180, 370, 731, 291))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 530, 131, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../ui/../pictures/horse_back.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pb_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_back.setGeometry(QtCore.QRect(30, 530, 131, 131))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        self.pb_back.setFont(font)
        self.pb_back.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 2px solid black;")
        self.pb_back.setObjectName("pb_back")
        self.pb_confirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_confirm.setGeometry(QtCore.QRect(760, 240, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        self.pb_confirm.setFont(font)
        self.pb_confirm.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pb_confirm.setObjectName("pb_confirm")
        self.l_folder = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.l_folder.setGeometry(QtCore.QRect(190, 220, 551, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        self.l_folder.setFont(font)
        self.l_folder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l_folder.setObjectName("l_folder")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 149, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        WindowAddVocabulariesNameFolder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WindowAddVocabulariesNameFolder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 23))
        self.menubar.setObjectName("menubar")
        WindowAddVocabulariesNameFolder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WindowAddVocabulariesNameFolder)
        self.statusbar.setObjectName("statusbar")
        WindowAddVocabulariesNameFolder.setStatusBar(self.statusbar)

        self.retranslateUi(WindowAddVocabulariesNameFolder)
        QtCore.QMetaObject.connectSlotsByName(WindowAddVocabulariesNameFolder)

    def retranslateUi(self, WindowAddVocabulariesNameFolder):
        _translate = QtCore.QCoreApplication.translate
        WindowAddVocabulariesNameFolder.setWindowTitle(_translate("WindowAddVocabulariesNameFolder", "Vokabeltrainer"))
        self.label.setText(_translate("WindowAddVocabulariesNameFolder", "Ordner bennen"))
        self.pb_back.setText(_translate("WindowAddVocabulariesNameFolder", "Zurück"))
        self.pb_confirm.setText(_translate("WindowAddVocabulariesNameFolder", "Bestätigen"))
        self.pb_confirm.setShortcut(_translate("WindowAddVocabulariesNameFolder", "Return"))
        self.label_3.setText(_translate("WindowAddVocabulariesNameFolder", "Geben Sie den Ordnernamen ein."))
