# Form implementation generated from reading ui file '../ui/window_folder_query.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowFolderQuery(object):
    def setupUi(self, WindowFolderQuery):
        WindowFolderQuery.setObjectName("WindowFolderQuery")
        WindowFolderQuery.resize(1124, 759)
        WindowFolderQuery.setStyleSheet("background-color: rgb(252, 217, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=WindowFolderQuery)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(180, 170, 731, 491))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 530, 131, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../ui/../pictures/horse_back.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pb_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_back.setGeometry(QtCore.QRect(30, 530, 131, 131))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        self.pb_back.setFont(font)
        self.pb_back.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 2px solid black;")
        self.pb_back.setObjectName("pb_back")
        self.verticalGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.verticalGroupBox.setGeometry(QtCore.QRect(690, 30, 251, 111))
        self.verticalGroupBox.setStyleSheet("background-color: rgb(170, 170, 255)")
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(1, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.verticalGroupBox)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.rb_eng = QtWidgets.QRadioButton(parent=self.verticalGroupBox)
        self.rb_eng.setStyleSheet("")
        self.rb_eng.setChecked(True)
        self.rb_eng.setObjectName("rb_eng")
        self.verticalLayout.addWidget(self.rb_eng)
        self.rb_de = QtWidgets.QRadioButton(parent=self.verticalGroupBox)
        self.rb_de.setStyleSheet("")
        self.rb_de.setObjectName("rb_de")
        self.verticalLayout.addWidget(self.rb_de)
        WindowFolderQuery.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WindowFolderQuery)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 23))
        self.menubar.setObjectName("menubar")
        WindowFolderQuery.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WindowFolderQuery)
        self.statusbar.setObjectName("statusbar")
        WindowFolderQuery.setStatusBar(self.statusbar)

        self.retranslateUi(WindowFolderQuery)
        QtCore.QMetaObject.connectSlotsByName(WindowFolderQuery)

    def retranslateUi(self, WindowFolderQuery):
        _translate = QtCore.QCoreApplication.translate
        WindowFolderQuery.setWindowTitle(_translate("WindowFolderQuery", "Vokabeltrainer"))
        self.label.setText(_translate("WindowFolderQuery", "Ordnerauswahl"))
        self.pb_back.setText(_translate("WindowFolderQuery", "Zurück"))
        self.label_3.setText(_translate("WindowFolderQuery", "Abfragerichtung"))
        self.rb_eng.setText(_translate("WindowFolderQuery", "Englisch -> Deutsch"))
        self.rb_de.setText(_translate("WindowFolderQuery", "Deutsch -> Englisch"))
